import { Resend } from "resend";
import { env } from "@/env";

const resend = new Resend(env.RESEND_API_KEY);

/**
 * Send a verification email.
 * Used for email verification with Better Auth.
 * Better Auth generates the URL and token automatically.
 * @param user - The user object containing the email address
 * @param url - The verification URL generated by Better Auth
 * @param token - The verification token (optional, for custom implementations)
 */
export const sendVerificationEmail = async ({
  user,
  url,
  token,
}: {
  user: { email: string };
  url: string;
  token: string;
}) => {
  await resend.emails.send({
    from: "mail@theflixsearch.com",
    to: user.email,
    subject: "Confirm your email",
    html: `<p>Click <a href="${url}">here</a> to confirm email.</p>`,
  });
};

/**
 * Send a password reset email.
 * Used for password reset with Better Auth.
 * Better Auth generates the URL and token automatically.
 * @param user - The user object containing the email address
 * @param url - The password reset URL generated by Better Auth
 * @param token - The password reset token (optional, for custom implementations)
 */
export const sendPasswordResetEmail = async ({
  user,
  url,
  token,
}: {
  user: { email: string };
  url: string;
  token: string;
}) => {
  await resend.emails.send({
    from: "mail@theflixsearch.com",
    to: user.email,
    subject: "Reset your password",
    html: `<p>Click <a href="${url}">here</a> to reset password.</p>`,
  });
};

/**
 * Send a two-factor email
 * Used for two-factor authentication.
 * Token is the 2FA code.
 * @param email - The email address to send the email to
 * @param token - The token to send in the email
 */
export const sendTwoFactorEmail = async (email: string, token: string) => {
  await resend.emails.send({
    from: "mail@theflixsearch.com",
    to: email,
    subject: "2FA code",
    html: `<p>Your 2FA code: ${token}</p>`,
  });
};
